In [384]:
import numpy as np
import random

A = np.array(
    (
        (1, -1/2, 0, 0, 0),
        (-1/2, 1, -1/2, 0, 0),
        (0, -1/2, 1, -1/2, 0),
        (0, 0, -1/2, 1, -1/2),
        (0, 0, 0, -1/2, 1)
    )
)

b = np.array(
    (0, 0, 0, 0, 1/2)
)

A_inv = np.linalg.inv(A)

x = A_inv.dot(b)

In [385]:
x

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

In [386]:
# solve the above using a V matrix

In [387]:
V = np.array(
    (0, 0, 0, 0, 0), dtype=float
)

reachable_state = np.array(
    (
        (0, 1, 0, 0, 0),
        (1, 0, 1, 0, 0),
        (0, 1, 0, 1, 0),
        (0, 0, 1, 0, 1),
        (0, 0, 0, 1, 0),
    )
)

r = np.array(
    (0, 0, 0, 0, 1), 
)

In [388]:
#can only go right, not left
#stop at the end
s = 0

for i in range(10):
    new_s = s + 1

In [389]:
reachable_state[0]

array([0, 1, 0, 0, 0])

In [390]:
alpha = 1
gamma = 1

for episode in range(1000):
    s = 3
    while True:
        a = random.choice((-1, 1))
        new_s = s + a
        reward = r[new_s]
        V[s] = V[s] + alpha*(reward + gamma*V[new_s] - V[s]) # fix this logic
        s = new_s
        if s < 0:
            break
        if s == 4:
            break

In [391]:
np.round(V, 2)

array([1., 1., 1., 1., 0.])

In [392]:
1/6

0.16666666666666666

In [393]:
2/6

0.3333333333333333

In [394]:
3/6

0.5

In [395]:
4/6

0.6666666666666666

In [396]:
5/6

0.8333333333333334